### ISSUE TITLE
`tec.TECBase.calc_electron_cooling_rate` raises AttributeError

### ISSUE THREAD

**Issue by jrsmith3** [jrsmith3/tec#72]
Upon successful instantiation of a `tec.TECBase` object, the `tec.TECBase.calc_electron_cooling_rate` unexpectedly raises an `AttributeError`. This exception was first noted in commit 32b9ec31bc545a7f4e44d8de139e01895c0bf6cd.

Example code
============
```python
from tec.electrode import Metal
from tec import TECBase

em = Metal(temp=1000., barrier=2., richardson=10.)
co = Metal(temp=300., barrier=1., richardson=10., position=10.)
t = TECBase(em, co)
t.calc_electron_cooling_rate()
```

Traceback
=========
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d3ee802e9141> in <module>()
      5 co = Metal(temp=300., barrier=1., richardson=10., position=10.)
      6 t = TECBase(em, co)
----> 7 t.calc_electron_cooling_rate()

/Users/jrsmith3/Documents/work/tec/tec/base.pyc in calc_electron_cooling_rate(self)
    272         unit_area = units.Quantity(1., "cm2")
    273 
--> 274         forward = unit_area * self.calc_forward_current_density() * (self.calc_max_motive_height + kT_E2) / constants.e.si
    275         back = unit_area * self.calc_back_current_density * (self.calc_max_motive_height + kT_C2) / constants.e.si
    276 

AttributeError: 'TECBase' object has no attribute 'calc_max_motive_height'
```

Environment
===========
See issue #66.

Additional information
======================
I first experienced this bug after writing some tests in commit 32b9ec31bc545a7f4e44d8de139e01895c0bf6cd; the specific test was `test/test_TECBase.py:CalculatorsReturnType.test_calc_electron_cooling_rate`.

Since `tec.TECBase.calc_heat_supply_rate` depends on `tec.TECBase.calc_electron_cooling_rate`, the test for it (namely `test/test_TECBase.py:CalculatorsReturnType.test_calc_heat_supply_rate`) exited with an error as well. Fixing this bug should make both tests green.

The offending code was introduced in a39cd815.

Solution
========
I think replacing instances of `self.calc_max_motive_height` with `self.calc_max_motive()` should fix this issue.
