### ISSUE TITLE
`tec.TECBase.calc_forward_current_density` raises AttributeError

### ISSUE THREAD

**Issue by jrsmith3** [jrsmith3/tec#70]
Upon successful instantiation of a `tec.TECBase` object, the `tec.TECBase.calc_forward_current_density` unexpectedly raises an `AttributeError`. This exception was first noted in commit 2e128006ac301398b260db32df1fa1351020a482.

Example code
============
```python
from tec.electrode import Metal
from tec import TECBase

em = Metal(temp=1000., barrier=2., richardson=10.)
co = Metal(temp=300., barrier=1., richardson=10., position=10.)
t = TECBase(em, co)
t.calc_forward_current_density()
```

Traceback
=========
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-bc994687953a> in <module>()
----> 1 t.calc_forward_current_density()

/Users/jrsmith3/Documents/work/tec/tec/base.pyc in calc_forward_current_density(self)
    129         :symbol: :math:`J_{f}`
    130         """
--> 131         sat_current_density = self.emitter.calc_saturation_current_density()
    132 
    133         if self.emitter.calc_barrier_ht() >= self.get_max_motive_ht():

AttributeError: 'Metal' object has no attribute 'calc_saturation_current_density'
```

Environment
===========
See issue #66.

Additional information
======================
I first experienced this bug after writing some tests in `test/test_TECBase.py` in commit 2e128006ac301398b260db32df1fa1351020a482; in this commit I added four tests:

* `test/test_TECBase.py:CalculatorsReturnType.calc_forward_current_density`
* `test/test_TECBase.py:CalculatorsReturnType.calc_back_current_density`
* `test/test_TECBase.py:CalculatorsReturnType.calc_output_current_density`
* `test/test_TECBase.py:CalculatorsReturnType.calc_output_power_density`

Each exited with an error as opposed to a failure based on the present issue. There is a similar problem with `tec.TECBase.calc_back_current_density`.

The offending code was introduced in a6764d23.

Solution
========
`tec.electrode.Metal` does not have a method named `calc_saturation_current_density`; I need to replace instances of that name with `calc_thermoelectron_current_density`.
