### ISSUE TITLE
`tec.TECBase.calc_forward_current_density` raises AttributeError

### ISSUE THREAD

**Issue by jrsmith3** [jrsmith3/tec#71]
Upon successful instantiation of a `tec.TECBase` object, the `tec.TECBase.calc_forward_current_density` unexpectedly raises an `AttributeError`. The present issue is related to, but different than #70 -- see the traceback below. I didn't notice this exception until commit 7c059f1f26114126aa2d320e80e51d80b49d7c7e by running the tests from commit 2e128006ac301398b260db32df1fa1351020a482. 

Example code
============
```python
from tec.electrode import Metal
from tec import TECBase

em = Metal(temp=1000., barrier=2., richardson=10.)
co = Metal(temp=300., barrier=1., richardson=10., position=10.)
t = TECBase(em, co)
t.calc_forward_current_density()
```

Traceback
=========
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-e221a1fc2e61> in <module>()
      5 co = Metal(temp=300., barrier=1., richardson=10., position=10.)
      6 t = TECBase(em, co)
----> 7 t.calc_forward_current_density()

/Users/jrsmith3/Documents/work/tec/tec/base.pyc in calc_forward_current_density(self)
    131         sat_current_density = self.emitter.calc_thermoelectron_current_density()
    132 
--> 133         if self.emitter.calc_barrier_ht() >= self.get_max_motive_ht():
    134             current_density = sat_current_density
    135         else:

AttributeError: 'Metal' object has no attribute 'calc_barrier_ht'
```

Environment
===========
See issue #66.

Additional information
======================
The offending code was introduced in a6764d23.

Solution
========
I don't think I spent sufficient time refactoring either `tec.TECBase.calc_forward_current_density` or `tec.TECBase.calc_back_current_density`; I need to refactor them properly.

**Comment by jrsmith3** [comment]
Closed as of 1730b63
